POST http://localhost:4000/api/signup
Content-Type: application/json

{
    "email": "2002399@gmail.com",
    "password": "dai123",
    "role": "STORE"
}

###

POST http://localhost:4000/api/signin
Content-Type: application/json

{
    "email": "2002399@gmail.com",
    "password": "dai123"
}

###

POST http://localhost:4000/api/user?id=Nguyen
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJjZDFjYzcyNy1iYzMyLTExZWQtOWVhMy0zYzdjM2YxOTMzZTMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiIyMDAyMzk5QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlNUT1JFIiwiZXhwIjoxNjc4MjAyNTg5LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAvIiwiYXVkIjoiKiJ9.O2Lf_LAz54WMSClSB-dDFVWdA_DjWBDgWN8cnZdrZAc

{
    "name": "Nguyễn Quốc Đại"
}

###


POST http://localhost:4000/api/store
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MDU2MjZiYi1iZmQwLTExZWQtYTY2Mi0zYzdjM2YxOTMzZTMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiIyMDAyMzk5QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkRFRkFVTFQiLCJleHAiOjE2Nzg3MTIwNDksImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMC8iLCJhdWQiOiIqIn0.mVnR0mwI6CRWqdQbl1x7u0sKbOOUBl-G16V6SuRkOJ0

{
    "name": "store 1",
    "location": "Ho Hoan Kiem",
    "group": "Ha Noi",
    "phonenumber": "0382889228"
}

###

GET  http://localhost:4000/api/store/7f936220-bc9b-11ed-9ea3-3c7c3f1933e3
Content-Type: application/json

###
GET http://localhost:4000/api/user/stores
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MDU2MjZiYi1iZmQwLTExZWQtYTY2Mi0zYzdjM2YxOTMzZTMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiIyMDAyMzk5QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkRFRkFVTFQiLCJleHAiOjE2Nzg3MTIwNDksImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMC8iLCJhdWQiOiIqIn0.mVnR0mwI6CRWqdQbl1x7u0sKbOOUBl-G16V6SuRkOJ0
