POST http://localhost:4000/api/signup
Content-Type: application/json

{
    "email": "2002399@gmail.com",
    "password": "dai123",
    "role": "STORE"
}

###

POST http://localhost:4000/api/signin
Content-Type: application/json

{
    "email": "2002399@gmail.com",
    "password": "dai123"
}

###

POST http://localhost:4000/api/user?id=Nguyen
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJhNGQ5NDI0My1jMjgyLTExZWQtODI0ZC0zYzdjM2YxOTMzZTMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJkYWlob2MyazIwQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlNUT1JFIiwiZXhwIjoxNjc4ODk2NTg4LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAvIiwiYXVkIjoiKiJ9.xcFM2SgVzlWpccM_pn4UZogtHrreUhIAq_b9S25Xwlg

{
    "name": "Nguyễn Quốc Đại"
}

###


POST http://localhost:4000/api/store
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIwOTQyOTQ2My1jODdjLTExZWQtOGFjYi0zYzdjM2YxOTMzZTMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiIyMDAyMzk5QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlNUT1JFIiwiZXhwIjoxNjc5NTUzNDU3LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAvIiwiYXVkIjoiKiJ9.rsv_EwHTINPhj9UubAkr3PhGLWXyYp5WK6SyDJKeY7c

{
    "name": "store 1",
    "location": "Ho Hoan Kiem",
    "group": "Ha Noi",
    "phonenumber": "0382889228"
}

###

GET  http://localhost:4000/api/store/7f936220-bc9b-11ed-9ea3-3c7c3f1933e3
Content-Type: application/json

###
GET http://localhost:4000/api/user/stores
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJjOWZlYTJmMy1jMjdmLTExZWQtODI0ZC0zYzdjM2YxOTMzZTMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiIyMDAyMzk5QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkRFRkFVTFQiLCJleHAiOjE2Nzg4OTkzMzUsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMC8iLCJhdWQiOiIqIn0.Hn42z7cPhLbIxi0A_MxnW0MFsz26OdJ21fkaXuiDu6w


###
POST http://localhost:4000/api/upload


###
DELETE http://localhost:4000/api/store/id/7c94a1c9-c3af-11ed-bf44-3c7c3f1933e3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI5NWJlZTEzMS1jMmY4LTExZWQtYTgxMC0zYzdjM2YxOTMzZTMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJkYWlob2MyazIwQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkRFRkFVTFQiLCJleHAiOjE2NzkwMTIwNjIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMC8iLCJhdWQiOiIqIn0.h99wpsN3qPoMwQ9OtZdwgps2d0i5m1PguTmXrchBQDw


###
POST http://127.0.0.1:4000/api/store/id/141b8a5f-c87c-11ed-8acb-3c7c3f1933e3/phones
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIwOTQyOTQ2My1jODdjLTExZWQtOGFjYi0zYzdjM2YxOTMzZTMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiIyMDAyMzk5QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlNUT1JFIiwiZXhwIjoxNjc5NTUzNDU3LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAvIiwiYXVkIjoiKiJ9.rsv_EwHTINPhj9UubAkr3PhGLWXyYp5WK6SyDJKeY7c
Content-Type: application/json

{
    "name": "Xiaomi Redmi Note 12",
    "images": "[\"/api/upload/e3ec4dd7-501b-4ed2-b6ba-8c252e9505b2?updateAt=-1399457247\",\"/api/upload/ed53cab9-2fd9-492b-8ef4-a19c2b215332?updateAt=-1399457247\"]",
    "phoneoffers": [
        {
            "color": "#8ED1FC",
            "count": "120",
            "price": "10000000",
            "storage": "4-128GB"
        },
        {
            "color": "#0693E3",
            "count": "120",
            "price": "12000000",
            "storage": "6-128GB"
        }
    ]
}

###

GET http://127.0.0.1:3000/api/store/id/09ea2fd7-c697-11ed-b848-3c7c3f1933e3/phones
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJmYjNhYWE0ZS1jNjk2LTExZWQtYjg0OC0zYzdjM2YxOTMzZTMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJkYWlob2MyazIwQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkRFRkFVTFQiLCJleHAiOjE2Nzk0NTgwNzQsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMC8iLCJhdWQiOiIqIn0.vG0_MAj7tKFFZsLq0Cg2JazBsPLNfEGGOW_4e--xtD4


###
DELETE http://localhost:4000/api/phone/id/7be047b4-c98d-11ed-960d-3c7c3f1933e3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3NWY1NmMxNC1jOThjLTExZWQtOTYwZC0zYzdjM2YxOTMzZTMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJkYWlob2MyazIwQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkRFRkFVTFQiLCJleHAiOjE2ODAzMzE5ODAsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMC8iLCJhdWQiOiIqIn0.cCg9wAnXoQIXCw-Bpv_XFu_dA2O-Cy7W4thrcKBq6Iw